in1 = input("Noun(Person, place, or thing): ")
in2 = input("Adjective: ")
in3 = input("Verb (Present tense): ")
in4 = input("Noun (Animal): ")
in5 = input("Adjective: ")
in6 = input("Verb (Present tense): ")
in7 = input("Noun (Object): ")
in8 = input("Verb (Past tense): ")
in9 = input("Adjective: ")
in10 = input("Noun (Food): ")
in11 = input("Adjective: ")
in12 = input("Verb (Present tense): ")
in13 = input("Adverb: ")
in14 = input("Noun (Person): ")
in15 = input("Verb (Present tense): ")

print()
print("\tOnce upon a time, in a faraway land, there was a " + in1 + ". It was a(n) " + in2 + " place, with " + in3 + " " + in4 + " running around. The sky was " + in5 +  " and the trees were " + in6 + " in the wind.")
print("\tOne day, a " + in7 + " appeared out of nowhere. It " + in8 + " away, leaving behind a trail of " + in9 + ". The people in the land gathered around, curious about what could be inside. They opened it to find a bunch of " + in10 + ".")
print("\tThe " + in11 + " " + in12 + " with excitement as they shared the " + in10 + " among themselves. Suddenly, " + in13 + ", a " + in14 + " appeared and demanded the " + in10 + " for themselves. The people refused and " + in15 + " away, leaving the " + in10 + " safe and sound. ")
print()
print("The end!")
  